// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using spotPriceCalc.Infrastructure.Persistence;

#nullable disable

namespace spotPriceCalc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719170515_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("spotPriceCalc.Domain.BiddingZone", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("bidding_zones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "10YAT-APG------L",
                            Latitude = 48.21m,
                            Longitude = 16.37m,
                            Name = "Austria",
                            TimeZoneId = "Europe/Vienna"
                        },
                        new
                        {
                            Id = 2,
                            Code = "10YBE----------2",
                            Latitude = 50.85m,
                            Longitude = 4.35m,
                            Name = "Belgium",
                            TimeZoneId = "Europe/Brussels"
                        },
                        new
                        {
                            Id = 3,
                            Code = "10YCA-BULGARIA-R",
                            Latitude = 42.70m,
                            Longitude = 23.32m,
                            Name = "Bulgaria",
                            TimeZoneId = "Europe/Sofia"
                        },
                        new
                        {
                            Id = 4,
                            Code = "10YCH-SWISSGRIDZ",
                            Latitude = 46.95m,
                            Longitude = 7.45m,
                            Name = "Switzerland",
                            TimeZoneId = "Europe/Zurich"
                        },
                        new
                        {
                            Id = 5,
                            Code = "10YCZ-CEPS-----N",
                            Latitude = 50.08m,
                            Longitude = 14.44m,
                            Name = "Czech Republic",
                            TimeZoneId = "Europe/Prague"
                        },
                        new
                        {
                            Id = 6,
                            Code = "10YSK-SEPS-----K",
                            Latitude = 48.15m,
                            Longitude = 17.11m,
                            Name = "Slovakia",
                            TimeZoneId = "Europe/Bratislava"
                        },
                        new
                        {
                            Id = 7,
                            Code = "10Y1001A1001A82H",
                            Latitude = 52.52m,
                            Longitude = 13.41m,
                            Name = "Germany-Luxembourg",
                            TimeZoneId = "Europe/Berlin"
                        },
                        new
                        {
                            Id = 8,
                            Code = "10Y1001A1001A39I",
                            Latitude = 59.44m,
                            Longitude = 24.75m,
                            Name = "Estonia",
                            TimeZoneId = "Europe/Tallinn"
                        },
                        new
                        {
                            Id = 9,
                            Code = "10YES-REE------0",
                            Latitude = 40.42m,
                            Longitude = -3.70m,
                            Name = "Spain",
                            TimeZoneId = "Europe/Madrid"
                        },
                        new
                        {
                            Id = 10,
                            Code = "10YFI-1--------U",
                            Latitude = 60.17m,
                            Longitude = 24.94m,
                            Name = "Finland",
                            TimeZoneId = "Europe/Helsinki"
                        },
                        new
                        {
                            Id = 11,
                            Code = "10YFR-RTE------C",
                            Latitude = 48.85m,
                            Longitude = 2.35m,
                            Name = "France",
                            TimeZoneId = "Europe/Paris"
                        },
                        new
                        {
                            Id = 12,
                            Code = "10YGR-HTSO-----Y",
                            Latitude = 37.98m,
                            Longitude = 23.73m,
                            Name = "Greece",
                            TimeZoneId = "Europe/Athens"
                        },
                        new
                        {
                            Id = 13,
                            Code = "10YHR-HEP------M",
                            Latitude = 45.81m,
                            Longitude = 15.98m,
                            Name = "Croatia",
                            TimeZoneId = "Europe/Zagreb"
                        },
                        new
                        {
                            Id = 14,
                            Code = "10YHU-MAVIR----U",
                            Latitude = 47.50m,
                            Longitude = 19.04m,
                            Name = "Hungary",
                            TimeZoneId = "Europe/Budapest"
                        },
                        new
                        {
                            Id = 15,
                            Code = "10YLT-1001A0008Q",
                            Latitude = 54.69m,
                            Longitude = 25.28m,
                            Name = "Lithuania",
                            TimeZoneId = "Europe/Vilnius"
                        },
                        new
                        {
                            Id = 16,
                            Code = "10YLV-1001A00074",
                            Latitude = 56.95m,
                            Longitude = 24.11m,
                            Name = "Latvia",
                            TimeZoneId = "Europe/Riga"
                        },
                        new
                        {
                            Id = 17,
                            Code = "10YNL----------L",
                            Latitude = 52.37m,
                            Longitude = 4.90m,
                            Name = "Netherlands",
                            TimeZoneId = "Europe/Amsterdam"
                        },
                        new
                        {
                            Id = 18,
                            Code = "10YPL-AREA-----S",
                            Latitude = 52.23m,
                            Longitude = 21.01m,
                            Name = "Poland",
                            TimeZoneId = "Europe/Warsaw"
                        },
                        new
                        {
                            Id = 19,
                            Code = "10YPT-REN------W",
                            Latitude = 38.72m,
                            Longitude = -9.14m,
                            Name = "Portugal",
                            TimeZoneId = "Europe/Lisbon"
                        },
                        new
                        {
                            Id = 20,
                            Code = "10YRO-TEL------P",
                            Latitude = 44.43m,
                            Longitude = 26.10m,
                            Name = "Romania",
                            TimeZoneId = "Europe/Bucharest"
                        },
                        new
                        {
                            Id = 21,
                            Code = "10YSI-ELES-----O",
                            Latitude = 46.05m,
                            Longitude = 14.51m,
                            Name = "Slovenia",
                            TimeZoneId = "Europe/Ljubljana"
                        },
                        new
                        {
                            Id = 22,
                            Code = "10Y1001A1001A44P",
                            Latitude = 65.58m,
                            Longitude = 22.15m,
                            Name = "Sweden SE1",
                            TimeZoneId = "Europe/Stockholm"
                        },
                        new
                        {
                            Id = 23,
                            Code = "10Y1001A1001A45N",
                            Latitude = 62.39m,
                            Longitude = 17.31m,
                            Name = "Sweden SE2",
                            TimeZoneId = "Europe/Stockholm"
                        },
                        new
                        {
                            Id = 24,
                            Code = "10Y1001A1001A46L",
                            Latitude = 59.33m,
                            Longitude = 18.07m,
                            Name = "Sweden SE3",
                            TimeZoneId = "Europe/Stockholm"
                        },
                        new
                        {
                            Id = 25,
                            Code = "10Y1001A1001A47J",
                            Latitude = 55.60m,
                            Longitude = 13.00m,
                            Name = "Sweden SE4",
                            TimeZoneId = "Europe/Stockholm"
                        },
                        new
                        {
                            Id = 26,
                            Code = "10YNO-1--------2",
                            Latitude = 59.91m,
                            Longitude = 10.75m,
                            Name = "Norway NO1",
                            TimeZoneId = "Europe/Oslo"
                        },
                        new
                        {
                            Id = 27,
                            Code = "10YNO-2--------T",
                            Latitude = 58.15m,
                            Longitude = 8.00m,
                            Name = "Norway NO2",
                            TimeZoneId = "Europe/Oslo"
                        },
                        new
                        {
                            Id = 28,
                            Code = "10YNO-3--------J",
                            Latitude = 63.43m,
                            Longitude = 10.39m,
                            Name = "Norway NO3",
                            TimeZoneId = "Europe/Oslo"
                        },
                        new
                        {
                            Id = 29,
                            Code = "10YNO-4--------9",
                            Latitude = 69.65m,
                            Longitude = 18.96m,
                            Name = "Norway NO4",
                            TimeZoneId = "Europe/Oslo"
                        },
                        new
                        {
                            Id = 30,
                            Code = "10Y1001A1001A48H",
                            Latitude = 60.39m,
                            Longitude = 5.32m,
                            Name = "Norway NO5",
                            TimeZoneId = "Europe/Oslo"
                        },
                        new
                        {
                            Id = 31,
                            Code = "10YDK-1--------W",
                            Latitude = 56.16m,
                            Longitude = 10.20m,
                            Name = "Denmark DK1",
                            TimeZoneId = "Europe/Copenhagen"
                        },
                        new
                        {
                            Id = 32,
                            Code = "10YDK-2--------M",
                            Latitude = 55.68m,
                            Longitude = 12.57m,
                            Name = "Denmark DK2",
                            TimeZoneId = "Europe/Copenhagen"
                        },
                        new
                        {
                            Id = 33,
                            Code = "10Y1001A1001A73I",
                            Latitude = 45.46m,
                            Longitude = 9.19m,
                            Name = "Italy North",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 34,
                            Code = "10Y1001A1001A70O",
                            Latitude = 43.77m,
                            Longitude = 11.26m,
                            Name = "Italy Centre-North",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 35,
                            Code = "10Y1001A1001A71M",
                            Latitude = 41.90m,
                            Longitude = 12.50m,
                            Name = "Italy Centre-South",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 36,
                            Code = "10Y1001A1001A788",
                            Latitude = 40.85m,
                            Longitude = 14.27m,
                            Name = "Italy South",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 37,
                            Code = "10Y1001A1001A74G",
                            Latitude = 39.22m,
                            Longitude = 9.12m,
                            Name = "Italy Sardinia",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 38,
                            Code = "10Y1001A1001A75E",
                            Latitude = 38.12m,
                            Longitude = 13.36m,
                            Name = "Italy Sicily",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 39,
                            Code = "10Y1001A1001A699",
                            Latitude = 40.63m,
                            Longitude = 17.94m,
                            Name = "Italy Brindisi",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 40,
                            Code = "10Y1001A1001A72K",
                            Latitude = 41.46m,
                            Longitude = 15.55m,
                            Name = "Italy Foggia",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 41,
                            Code = "10Y1001C--00096J",
                            Latitude = 38.91m,
                            Longitude = 16.59m,
                            Name = "Italy Calabria",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 42,
                            Code = "10Y1001A1001A76C",
                            Latitude = 37.16m,
                            Longitude = 15.18m,
                            Name = "Italy Priolo",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 43,
                            Code = "10Y1001A1001A77A",
                            Latitude = 39.57m,
                            Longitude = 16.63m,
                            Name = "Italy Rossano",
                            TimeZoneId = "Europe/Rome"
                        });
                });

            modelBuilder.Entity("spotPriceCalc.Infrastructure.Persistence.Entities.SpotPriceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BiddingZoneId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,4)");

                    b.Property<DateTime>("To")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BiddingZoneId", "From")
                        .IsUnique();

                    b.ToTable("spot_prices", (string)null);
                });

            modelBuilder.Entity("spotPriceCalc.Infrastructure.Persistence.Entities.TemperatureReadingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BiddingZoneId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TemperatureC")
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTime>("TimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BiddingZoneId", "TimeUtc")
                        .IsUnique();

                    b.ToTable("temperature_readings", (string)null);
                });

            modelBuilder.Entity("spotPriceCalc.Infrastructure.Persistence.Entities.SpotPriceEntity", b =>
                {
                    b.HasOne("spotPriceCalc.Domain.BiddingZone", null)
                        .WithMany()
                        .HasForeignKey("BiddingZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("spotPriceCalc.Infrastructure.Persistence.Entities.TemperatureReadingEntity", b =>
                {
                    b.HasOne("spotPriceCalc.Domain.BiddingZone", null)
                        .WithMany()
                        .HasForeignKey("BiddingZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
