// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using spotPriceCalc.Infrastructure.Persistence;

#nullable disable

namespace spotPriceCalc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("spotPriceCalc.Domain.BiddingZone", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("bidding_zones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "10YAT-APG------L",
                            Latitude = 48.210000000000001,
                            Longitude = 16.370000000000001,
                            Name = "Austria",
                            TimeZoneId = "Europe/Vienna"
                        },
                        new
                        {
                            Id = 2,
                            Code = "10YBE----------2",
                            Latitude = 50.850000000000001,
                            Longitude = 4.3499999999999996,
                            Name = "Belgium",
                            TimeZoneId = "Europe/Brussels"
                        },
                        new
                        {
                            Id = 3,
                            Code = "10YCA-BULGARIA-R",
                            Latitude = 42.700000000000003,
                            Longitude = 23.32,
                            Name = "Bulgaria",
                            TimeZoneId = "Europe/Sofia"
                        },
                        new
                        {
                            Id = 4,
                            Code = "10YCH-SWISSGRIDZ",
                            Latitude = 46.950000000000003,
                            Longitude = 7.4500000000000002,
                            Name = "Switzerland",
                            TimeZoneId = "Europe/Zurich"
                        },
                        new
                        {
                            Id = 5,
                            Code = "10YCZ-CEPS-----N",
                            Latitude = 50.079999999999998,
                            Longitude = 14.44,
                            Name = "Czech Republic",
                            TimeZoneId = "Europe/Prague"
                        },
                        new
                        {
                            Id = 6,
                            Code = "10YSK-SEPS-----K",
                            Latitude = 48.149999999999999,
                            Longitude = 17.109999999999999,
                            Name = "Slovakia",
                            TimeZoneId = "Europe/Bratislava"
                        },
                        new
                        {
                            Id = 7,
                            Code = "10Y1001A1001A82H",
                            Latitude = 52.520000000000003,
                            Longitude = 13.41,
                            Name = "Germany-Luxembourg",
                            TimeZoneId = "Europe/Berlin"
                        },
                        new
                        {
                            Id = 8,
                            Code = "10Y1001A1001A39I",
                            Latitude = 59.439999999999998,
                            Longitude = 24.75,
                            Name = "Estonia",
                            TimeZoneId = "Europe/Tallinn"
                        },
                        new
                        {
                            Id = 9,
                            Code = "10YES-REE------0",
                            Latitude = 40.420000000000002,
                            Longitude = -3.7000000000000002,
                            Name = "Spain",
                            TimeZoneId = "Europe/Madrid"
                        },
                        new
                        {
                            Id = 10,
                            Code = "10YFI-1--------U",
                            Latitude = 60.170000000000002,
                            Longitude = 24.940000000000001,
                            Name = "Finland",
                            TimeZoneId = "Europe/Helsinki"
                        },
                        new
                        {
                            Id = 11,
                            Code = "10YFR-RTE------C",
                            Latitude = 48.850000000000001,
                            Longitude = 2.3500000000000001,
                            Name = "France",
                            TimeZoneId = "Europe/Paris"
                        },
                        new
                        {
                            Id = 12,
                            Code = "10YGR-HTSO-----Y",
                            Latitude = 37.979999999999997,
                            Longitude = 23.73,
                            Name = "Greece",
                            TimeZoneId = "Europe/Athens"
                        },
                        new
                        {
                            Id = 13,
                            Code = "10YHR-HEP------M",
                            Latitude = 45.810000000000002,
                            Longitude = 15.98,
                            Name = "Croatia",
                            TimeZoneId = "Europe/Zagreb"
                        },
                        new
                        {
                            Id = 14,
                            Code = "10YHU-MAVIR----U",
                            Latitude = 47.5,
                            Longitude = 19.039999999999999,
                            Name = "Hungary",
                            TimeZoneId = "Europe/Budapest"
                        },
                        new
                        {
                            Id = 15,
                            Code = "10YLT-1001A0008Q",
                            Latitude = 54.689999999999998,
                            Longitude = 25.280000000000001,
                            Name = "Lithuania",
                            TimeZoneId = "Europe/Vilnius"
                        },
                        new
                        {
                            Id = 16,
                            Code = "10YLV-1001A00074",
                            Latitude = 56.950000000000003,
                            Longitude = 24.109999999999999,
                            Name = "Latvia",
                            TimeZoneId = "Europe/Riga"
                        },
                        new
                        {
                            Id = 17,
                            Code = "10YNL----------L",
                            Latitude = 52.369999999999997,
                            Longitude = 4.9000000000000004,
                            Name = "Netherlands",
                            TimeZoneId = "Europe/Amsterdam"
                        },
                        new
                        {
                            Id = 18,
                            Code = "10YPL-AREA-----S",
                            Latitude = 52.229999999999997,
                            Longitude = 21.010000000000002,
                            Name = "Poland",
                            TimeZoneId = "Europe/Warsaw"
                        },
                        new
                        {
                            Id = 19,
                            Code = "10YPT-REN------W",
                            Latitude = 38.719999999999999,
                            Longitude = -9.1400000000000006,
                            Name = "Portugal",
                            TimeZoneId = "Europe/Lisbon"
                        },
                        new
                        {
                            Id = 20,
                            Code = "10YRO-TEL------P",
                            Latitude = 44.43,
                            Longitude = 26.100000000000001,
                            Name = "Romania",
                            TimeZoneId = "Europe/Bucharest"
                        },
                        new
                        {
                            Id = 21,
                            Code = "10YSI-ELES-----O",
                            Latitude = 46.049999999999997,
                            Longitude = 14.51,
                            Name = "Slovenia",
                            TimeZoneId = "Europe/Ljubljana"
                        },
                        new
                        {
                            Id = 22,
                            Code = "10Y1001A1001A44P",
                            Latitude = 65.579999999999998,
                            Longitude = 22.149999999999999,
                            Name = "Sweden SE1",
                            TimeZoneId = "Europe/Stockholm"
                        },
                        new
                        {
                            Id = 23,
                            Code = "10Y1001A1001A45N",
                            Latitude = 62.390000000000001,
                            Longitude = 17.309999999999999,
                            Name = "Sweden SE2",
                            TimeZoneId = "Europe/Stockholm"
                        },
                        new
                        {
                            Id = 24,
                            Code = "10Y1001A1001A46L",
                            Latitude = 59.329999999999998,
                            Longitude = 18.07,
                            Name = "Sweden SE3",
                            TimeZoneId = "Europe/Stockholm"
                        },
                        new
                        {
                            Id = 25,
                            Code = "10Y1001A1001A47J",
                            Latitude = 55.600000000000001,
                            Longitude = 13.0,
                            Name = "Sweden SE4",
                            TimeZoneId = "Europe/Stockholm"
                        },
                        new
                        {
                            Id = 26,
                            Code = "10YNO-1--------2",
                            Latitude = 59.909999999999997,
                            Longitude = 10.75,
                            Name = "Norway NO1",
                            TimeZoneId = "Europe/Oslo"
                        },
                        new
                        {
                            Id = 27,
                            Code = "10YNO-2--------T",
                            Latitude = 58.149999999999999,
                            Longitude = 8.0,
                            Name = "Norway NO2",
                            TimeZoneId = "Europe/Oslo"
                        },
                        new
                        {
                            Id = 28,
                            Code = "10YNO-3--------J",
                            Latitude = 63.43,
                            Longitude = 10.390000000000001,
                            Name = "Norway NO3",
                            TimeZoneId = "Europe/Oslo"
                        },
                        new
                        {
                            Id = 29,
                            Code = "10YNO-4--------9",
                            Latitude = 69.650000000000006,
                            Longitude = 18.960000000000001,
                            Name = "Norway NO4",
                            TimeZoneId = "Europe/Oslo"
                        },
                        new
                        {
                            Id = 30,
                            Code = "10Y1001A1001A48H",
                            Latitude = 60.390000000000001,
                            Longitude = 5.3200000000000003,
                            Name = "Norway NO5",
                            TimeZoneId = "Europe/Oslo"
                        },
                        new
                        {
                            Id = 31,
                            Code = "10YDK-1--------W",
                            Latitude = 56.159999999999997,
                            Longitude = 10.199999999999999,
                            Name = "Denmark DK1",
                            TimeZoneId = "Europe/Copenhagen"
                        },
                        new
                        {
                            Id = 32,
                            Code = "10YDK-2--------M",
                            Latitude = 55.68,
                            Longitude = 12.57,
                            Name = "Denmark DK2",
                            TimeZoneId = "Europe/Copenhagen"
                        },
                        new
                        {
                            Id = 33,
                            Code = "10Y1001A1001A73I",
                            Latitude = 45.460000000000001,
                            Longitude = 9.1899999999999995,
                            Name = "Italy North",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 34,
                            Code = "10Y1001A1001A70O",
                            Latitude = 43.770000000000003,
                            Longitude = 11.26,
                            Name = "Italy Centre-North",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 35,
                            Code = "10Y1001A1001A71M",
                            Latitude = 41.899999999999999,
                            Longitude = 12.5,
                            Name = "Italy Centre-South",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 36,
                            Code = "10Y1001A1001A788",
                            Latitude = 40.850000000000001,
                            Longitude = 14.27,
                            Name = "Italy South",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 37,
                            Code = "10Y1001A1001A74G",
                            Latitude = 39.219999999999999,
                            Longitude = 9.1199999999999992,
                            Name = "Italy Sardinia",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 38,
                            Code = "10Y1001A1001A75E",
                            Latitude = 38.119999999999997,
                            Longitude = 13.359999999999999,
                            Name = "Italy Sicily",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 39,
                            Code = "10Y1001A1001A699",
                            Latitude = 40.630000000000003,
                            Longitude = 17.940000000000001,
                            Name = "Italy Brindisi",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 40,
                            Code = "10Y1001A1001A72K",
                            Latitude = 41.460000000000001,
                            Longitude = 15.550000000000001,
                            Name = "Italy Foggia",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 41,
                            Code = "10Y1001C--00096J",
                            Latitude = 38.909999999999997,
                            Longitude = 16.59,
                            Name = "Italy Calabria",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 42,
                            Code = "10Y1001A1001A76C",
                            Latitude = 37.159999999999997,
                            Longitude = 15.18,
                            Name = "Italy Priolo",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 43,
                            Code = "10Y1001A1001A77A",
                            Latitude = 39.57,
                            Longitude = 16.629999999999999,
                            Name = "Italy Rossano",
                            TimeZoneId = "Europe/Rome"
                        });
                });

            modelBuilder.Entity("spotPriceCalc.Infrastructure.Persistence.Entities.SpotPriceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BiddingZoneId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,4)");

                    b.Property<DateTime>("To")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BiddingZoneId", "From")
                        .IsUnique();

                    b.ToTable("spot_prices", (string)null);
                });

            modelBuilder.Entity("spotPriceCalc.Infrastructure.Persistence.Entities.TemperatureReadingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BiddingZoneId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TemperatureC")
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTime>("TimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BiddingZoneId", "TimeUtc")
                        .IsUnique();

                    b.ToTable("temperature_readings", (string)null);
                });

            modelBuilder.Entity("spotPriceCalc.Infrastructure.Persistence.Entities.SpotPriceEntity", b =>
                {
                    b.HasOne("spotPriceCalc.Domain.BiddingZone", null)
                        .WithMany()
                        .HasForeignKey("BiddingZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("spotPriceCalc.Infrastructure.Persistence.Entities.TemperatureReadingEntity", b =>
                {
                    b.HasOne("spotPriceCalc.Domain.BiddingZone", null)
                        .WithMany()
                        .HasForeignKey("BiddingZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
