// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using spotPriceCalc.Infrastructure.Persistence;

#nullable disable

namespace spotPriceCalc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("spotPriceCalc.Domain.BiddingZone", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("bidding_zones", (string)null);
                });

            modelBuilder.Entity("spotPriceCalc.Infrastructure.Persistence.Entities.SpotPriceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BiddingZoneId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,4)");

                    b.Property<int?>("Quantile")
                        .HasColumnType("integer");

                    b.Property<DateTime>("To")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BiddingZoneId", "From")
                        .IsUnique();

                    b.ToTable("spot_prices", (string)null);
                });

            modelBuilder.Entity("spotPriceCalc.Infrastructure.Persistence.Entities.TemperatureReadingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BiddingZoneId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TemperatureC")
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTime>("TimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BiddingZoneId", "TimeUtc")
                        .IsUnique();

                    b.ToTable("temperature_readings", (string)null);
                });

            modelBuilder.Entity("spotPriceCalc.Infrastructure.Persistence.Entities.SpotPriceEntity", b =>
                {
                    b.HasOne("spotPriceCalc.Domain.BiddingZone", null)
                        .WithMany()
                        .HasForeignKey("BiddingZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("spotPriceCalc.Infrastructure.Persistence.Entities.TemperatureReadingEntity", b =>
                {
                    b.HasOne("spotPriceCalc.Domain.BiddingZone", null)
                        .WithMany()
                        .HasForeignKey("BiddingZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
